version: "3"

services:
  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongodb-volume:/data/db
    ports:
      - 27017:27017
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment: 
      - MONGO_HOST=mongodb
      - MONGO_USERNAME=root
      - MONGO_PASSWORD=password
      - MONGO_DB_NAME=tictactoe
    volumes: 
      - ./:/home/app
    ports: 
      - 2567:2567
    depends_on: 
      - mongodb

volumes: 
  mongodb-volume: